"""Add image url to ingredient

Revision ID: cbede47f7bc9
Revises: 7ee8c475498f
Create Date: 2025-08-15 16:59:50.303552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbede47f7bc9'
down_revision: Union[str, None] = '7ee8c475498f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredient', sa.Column('image_url', sa.String(length=2000), nullable=True))
    op.alter_column('working_hours', 'is_holiday',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('working_hours', 'is_holiday',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('ingredient', 'image_url')
    # ### end Alembic commands ###
