"""Add holiday to working_hours

Revision ID: 7ee8c475498f
Revises: 054323605cfd
Create Date: 2025-07-30 17:33:47.527970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ee8c475498f'
down_revision: Union[str, None] = '054323605cfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('working_hours', sa.Column('is_holiday', sa.Boolean(), nullable=True))
    
    # Устанавливаем значение по умолчанию для существующих записей
    op.execute("UPDATE working_hours SET is_holiday = true WHERE is_holiday IS NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('working_hours', 'is_holiday')
    # ### end Alembic commands ###
