"""Add quantity to order_item, add order.status as enum

Revision ID: bf09f8538801
Revises: 14154252d52a
Create Date: 2025-08-30 11:05:05.374415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf09f8538801'
down_revision: Union[str, None] = '14154252d52a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the enum type first
    order_status_enum = sa.Enum('created', 'in_progress', 'done', 'cancelled', name='order_status_enum')
    order_status_enum.create(op.get_bind())
    
    # Add quantity column to order_item
    op.add_column('order_item', sa.Column('quantity', sa.Integer(), nullable=False, server_default='1'))
    
    # Convert status column to enum with explicit casting
    op.alter_column('order', 'status',
               existing_type=sa.VARCHAR(length=100),
               type_=order_status_enum,
               postgresql_using='status::order_status_enum',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Convert enum back to varchar
    op.alter_column('order', 'status',
               existing_type=sa.Enum('created', 'in_progress', 'done', 'cancelled', name='order_status_enum'),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    
    # Drop the enum type
    order_status_enum = sa.Enum('created', 'in_progress', 'done', 'cancelled', name='order_status_enum')
    order_status_enum.drop(op.get_bind())
    
    # Remove quantity column
    op.drop_column('order_item', 'quantity')
    # ### end Alembic commands ###
