"""Edit UserAddress nullable

Revision ID: a1aa47302532
Revises: e6144d5eae9f
Create Date: 2025-09-24 23:51:31.817348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1aa47302532'
down_revision: Union[str, None] = 'e6144d5eae9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_address', 'entrance',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('user_address', 'floor',
               existing_type=sa.SMALLINT(),
               nullable=True)
    op.alter_column('user_address', 'apartment',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_address', 'apartment',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('user_address', 'floor',
               existing_type=sa.SMALLINT(),
               nullable=False)
    op.alter_column('user_address', 'entrance',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    # ### end Alembic commands ###
