"""Add working_hours and change food

Revision ID: 315f6116cf1a
Revises: 1bb0d20c4ae5
Create Date: 2025-07-08 17:13:03.376253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = '315f6116cf1a'
down_revision: Union[str, None] = '1bb0d20c4ae5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feature',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('icon_url', sa.String(length=2000), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('restaurant_feature',
    sa.Column('restaurant_id', sa.Integer(), nullable=True),
    sa.Column('feature_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['feature_id'], ['feature.id'], ),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurant.id'], )
    )
    op.add_column('food', sa.Column('sub_name', sa.String(length=200), nullable=True))
    op.add_column('food', sa.Column('image_url', sa.String(length=2000), nullable=True))
    op.add_column('restaurant', sa.Column('phone', sqlalchemy_utils.types.phone_number.PhoneNumberType(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurant', 'phone')
    op.drop_column('food', 'image_url')
    op.drop_column('food', 'sub_name')
    op.drop_table('restaurant_feature')
    op.drop_table('feature')
    # ### end Alembic commands ###
