"""Fix

Revision ID: 14154252d52a
Revises: 0aabb6b0bf4e
Create Date: 2025-08-25 21:05:48.984872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '14154252d52a'
down_revision: Union[str, None] = '0aabb6b0bf4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_token', sa.Column('expires_at', sa.DateTime(), nullable=False))
    op.drop_column('refresh_token', 'axpires_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_token', sa.Column('axpires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('refresh_token', 'expires_at')
    # ### end Alembic commands ###
