"""Edit UserAddress nullable, remove is_removable from ingredient assoc, add need_addings to category

Revision ID: e6144d5eae9f
Revises: 24b834b30b79
Create Date: 2025-09-24 11:27:55.859972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6144d5eae9f'
down_revision: Union[str, None] = '24b834b30b79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('food_ingredient', 'is_removable')
    op.add_column('menu_category', sa.Column('need_addings', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menu_category', 'need_addings')
    op.add_column('food_ingredient', sa.Column('is_removable', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
