"""add cooked to order status, add unqiue code to order

Revision ID: 230e07155bad
Revises: 4a405c839c80
Create Date: 2025-10-21 13:11:05.255778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '230e07155bad'
down_revision: Union[str, None] = '4a405c839c80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("ALTER TYPE order_status_enum RENAME TO order_status_enum_old")

    order_status_enum = sa.Enum('created', 'in_progress', 'cooked', 'in_delivery', 'done', 'cancelled', name='order_status_enum')
    order_status_enum.create(op.get_bind())

    # Добавлено явное преобразование для 'in_delivery'
    op.execute('''
        ALTER TABLE "order" 
        ALTER COLUMN status TYPE order_status_enum 
        USING CASE 
            WHEN status = 'created' THEN 'created'::order_status_enum
            WHEN status = 'in_progress' THEN 'in_progress'::order_status_enum
            WHEN status = 'in_delivery' THEN 'in_delivery'::order_status_enum
            WHEN status = 'done' THEN 'done'::order_status_enum
            WHEN status = 'cancelled' THEN 'cancelled'::order_status_enum
            ELSE 'created'::order_status_enum
        END
    ''')

    op.execute('DROP TYPE order_status_enum_old')
    op.add_column('order', sa.Column('unique_code', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Переименовываем старый enum
    op.execute("ALTER TYPE order_status_enum RENAME TO order_status_enum_old")

    # Создаем старый enum
    order_status_enum = sa.Enum('created', 'in_progress', 'in_delivery', 'done', 'cancelled', name='order_status_enum')
    order_status_enum.create(op.get_bind())

    # Конвертируем данные обратно
    op.execute('''
        ALTER TABLE "order"
        ALTER COLUMN status TYPE order_status_enum
        USING CASE
            WHEN status = 'created' THEN 'created'::order_status_enum
            WHEN status = 'cooked' THEN 'done'::order_status_enum
            WHEN status = 'in_progress' THEN 'in_progress'::order_status_enum
            WHEN status = 'in_delivery' THEN 'in_delivery'::order_status_enum
            WHEN status = 'done' THEN 'done'::order_status_enum
            WHEN status = 'cancelled' THEN 'cancelled'::order_status_enum
            ELSE 'created'::order_status_enum
        END
    ''')

    op.execute('DROP TYPE order_status_enum_old')

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'unique_code')
    # ### end Alembic commands ###
