"""Add ondelete, change columns

Revision ID: 054323605cfd
Revises: e3a64f7f3d59
Create Date: 2025-07-24 14:01:35.454618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '054323605cfd'
down_revision: Union[str, None] = 'e3a64f7f3d59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('__order_item_added_ingredient_order_item_id_fkey', '__order_item_added_ingredient', type_='foreignkey')
    op.drop_constraint('__order_item_added_ingredient_added_id_fkey', '__order_item_added_ingredient', type_='foreignkey')
    op.create_foreign_key(None, '__order_item_added_ingredient', 'ingredient', ['added_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, '__order_item_added_ingredient', 'order_item', ['order_item_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('__order_item_removed_ingredient_removed_id_fkey', '__order_item_removed_ingredient', type_='foreignkey')
    op.drop_constraint('__order_item_removed_ingredient_order_item_id_fkey', '__order_item_removed_ingredient', type_='foreignkey')
    op.create_foreign_key(None, '__order_item_removed_ingredient', 'order_item', ['order_item_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, '__order_item_removed_ingredient', 'ingredient', ['removed_id'], ['id'], ondelete='CASCADE')
    op.add_column('food', sa.Column('measure_name', sa.String(length=50), nullable=True))
    op.alter_column('food', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('food_category_id_fkey', 'food', type_='foreignkey')
    op.create_foreign_key(None, 'food', 'menu_category', ['category_id'], ['id'], ondelete='SET NULL')
    op.drop_column('food_characteristic', 'measure_name')
    op.drop_constraint('food_characteristic_variant_variant_id_fkey', 'food_characteristic_variant', type_='foreignkey')
    op.drop_constraint('food_characteristic_variant_characteristic_id_fkey', 'food_characteristic_variant', type_='foreignkey')
    op.create_foreign_key(None, 'food_characteristic_variant', 'food_characteristic', ['characteristic_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'food_characteristic_variant', 'food_variant', ['variant_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('food_ingredient_food_id_fkey', 'food_ingredient', type_='foreignkey')
    op.drop_constraint('food_ingredient_ingredient_id_fkey', 'food_ingredient', type_='foreignkey')
    op.create_foreign_key(None, 'food_ingredient', 'ingredient', ['ingredient_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'food_ingredient', 'food', ['food_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('food_variant_food_id_fkey', 'food_variant', type_='foreignkey')
    op.create_foreign_key(None, 'food_variant', 'food', ['food_id'], ['id'], ondelete='CASCADE')
    op.alter_column('order', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('order_restaurant_id_fkey', 'order', type_='foreignkey')
    op.drop_constraint('order_address_id_fkey', 'order', type_='foreignkey')
    op.drop_constraint('order_user_id_fkey', 'order', type_='foreignkey')
    op.create_foreign_key(None, 'order', 'user_address', ['address_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'order', 'restaurant', ['restaurant_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'order', 'user', ['user_id'], ['id'], ondelete='RESTRICT')
    op.drop_constraint('order_item_order_id_fkey', 'order_item', type_='foreignkey')
    op.drop_constraint('order_item_food_id_fkey', 'order_item', type_='foreignkey')
    op.create_foreign_key(None, 'order_item', 'order', ['order_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'order_item', 'food', ['food_id'], ['id'], ondelete='RESTRICT')
    op.drop_constraint('restaurant_city_id_fkey', 'restaurant', type_='foreignkey')
    op.create_foreign_key(None, 'restaurant', 'city', ['city_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('restaurant_category_restaurant_id_fkey', 'restaurant_category', type_='foreignkey')
    op.drop_constraint('restaurant_category_category_id_fkey', 'restaurant_category', type_='foreignkey')
    op.create_foreign_key(None, 'restaurant_category', 'menu_category', ['category_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'restaurant_category', 'restaurant', ['restaurant_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('restaurant_feature_feature_id_fkey', 'restaurant_feature', type_='foreignkey')
    op.drop_constraint('restaurant_feature_restaurant_id_fkey', 'restaurant_feature', type_='foreignkey')
    op.create_foreign_key(None, 'restaurant_feature', 'feature', ['feature_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'restaurant_feature', 'restaurant', ['restaurant_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('restaurant_food_disabled_restaurant_id_fkey', 'restaurant_food_disabled', type_='foreignkey')
    op.drop_constraint('restaurant_food_disabled_food_id_fkey', 'restaurant_food_disabled', type_='foreignkey')
    op.create_foreign_key(None, 'restaurant_food_disabled', 'food', ['food_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'restaurant_food_disabled', 'restaurant', ['restaurant_id'], ['id'], ondelete='CASCADE')
    op.add_column('user', sa.Column('is_removed', sa.Boolean(), nullable=False))
    op.add_column('user_address', sa.Column('is_removed', sa.Boolean(), nullable=False))
    op.drop_constraint('user_address_user_id_fkey', 'user_address', type_='foreignkey')
    op.create_foreign_key(None, 'user_address', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('user_favorite_user_id_fkey', 'user_favorite', type_='foreignkey')
    op.drop_constraint('user_favorite_food_id_fkey', 'user_favorite', type_='foreignkey')
    op.create_foreign_key(None, 'user_favorite', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_favorite', 'food', ['food_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('working_hours_restaurant_id_fkey', 'working_hours', type_='foreignkey')
    op.create_foreign_key(None, 'working_hours', 'restaurant', ['restaurant_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'working_hours', type_='foreignkey')
    op.create_foreign_key('working_hours_restaurant_id_fkey', 'working_hours', 'restaurant', ['restaurant_id'], ['id'])
    op.drop_constraint(None, 'user_favorite', type_='foreignkey')
    op.drop_constraint(None, 'user_favorite', type_='foreignkey')
    op.create_foreign_key('user_favorite_food_id_fkey', 'user_favorite', 'food', ['food_id'], ['id'])
    op.create_foreign_key('user_favorite_user_id_fkey', 'user_favorite', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'user_address', type_='foreignkey')
    op.create_foreign_key('user_address_user_id_fkey', 'user_address', 'user', ['user_id'], ['id'])
    op.drop_column('user_address', 'is_removed')
    op.drop_column('user', 'is_removed')
    op.drop_constraint(None, 'restaurant_food_disabled', type_='foreignkey')
    op.drop_constraint(None, 'restaurant_food_disabled', type_='foreignkey')
    op.create_foreign_key('restaurant_food_disabled_food_id_fkey', 'restaurant_food_disabled', 'food', ['food_id'], ['id'])
    op.create_foreign_key('restaurant_food_disabled_restaurant_id_fkey', 'restaurant_food_disabled', 'restaurant', ['restaurant_id'], ['id'])
    op.drop_constraint(None, 'restaurant_feature', type_='foreignkey')
    op.drop_constraint(None, 'restaurant_feature', type_='foreignkey')
    op.create_foreign_key('restaurant_feature_restaurant_id_fkey', 'restaurant_feature', 'restaurant', ['restaurant_id'], ['id'])
    op.create_foreign_key('restaurant_feature_feature_id_fkey', 'restaurant_feature', 'feature', ['feature_id'], ['id'])
    op.drop_constraint(None, 'restaurant_category', type_='foreignkey')
    op.drop_constraint(None, 'restaurant_category', type_='foreignkey')
    op.create_foreign_key('restaurant_category_category_id_fkey', 'restaurant_category', 'menu_category', ['category_id'], ['id'])
    op.create_foreign_key('restaurant_category_restaurant_id_fkey', 'restaurant_category', 'restaurant', ['restaurant_id'], ['id'])
    op.drop_constraint(None, 'restaurant', type_='foreignkey')
    op.create_foreign_key('restaurant_city_id_fkey', 'restaurant', 'city', ['city_id'], ['id'])
    op.drop_constraint(None, 'order_item', type_='foreignkey')
    op.drop_constraint(None, 'order_item', type_='foreignkey')
    op.create_foreign_key('order_item_food_id_fkey', 'order_item', 'food', ['food_id'], ['id'])
    op.create_foreign_key('order_item_order_id_fkey', 'order_item', 'order', ['order_id'], ['id'])
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.create_foreign_key('order_user_id_fkey', 'order', 'user', ['user_id'], ['id'])
    op.create_foreign_key('order_address_id_fkey', 'order', 'user_address', ['address_id'], ['id'])
    op.create_foreign_key('order_restaurant_id_fkey', 'order', 'restaurant', ['restaurant_id'], ['id'])
    op.alter_column('order', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'food_variant', type_='foreignkey')
    op.create_foreign_key('food_variant_food_id_fkey', 'food_variant', 'food', ['food_id'], ['id'])
    op.drop_constraint(None, 'food_ingredient', type_='foreignkey')
    op.drop_constraint(None, 'food_ingredient', type_='foreignkey')
    op.create_foreign_key('food_ingredient_ingredient_id_fkey', 'food_ingredient', 'ingredient', ['ingredient_id'], ['id'])
    op.create_foreign_key('food_ingredient_food_id_fkey', 'food_ingredient', 'food', ['food_id'], ['id'])
    op.drop_constraint(None, 'food_characteristic_variant', type_='foreignkey')
    op.drop_constraint(None, 'food_characteristic_variant', type_='foreignkey')
    op.create_foreign_key('food_characteristic_variant_characteristic_id_fkey', 'food_characteristic_variant', 'food_characteristic', ['characteristic_id'], ['id'])
    op.create_foreign_key('food_characteristic_variant_variant_id_fkey', 'food_characteristic_variant', 'food_variant', ['variant_id'], ['id'])
    op.add_column('food_characteristic', sa.Column('measure_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'food', type_='foreignkey')
    op.create_foreign_key('food_category_id_fkey', 'food', 'menu_category', ['category_id'], ['id'])
    op.alter_column('food', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('food', 'measure_name')
    op.drop_constraint(None, '__order_item_removed_ingredient', type_='foreignkey')
    op.drop_constraint(None, '__order_item_removed_ingredient', type_='foreignkey')
    op.create_foreign_key('__order_item_removed_ingredient_order_item_id_fkey', '__order_item_removed_ingredient', 'order_item', ['order_item_id'], ['id'])
    op.create_foreign_key('__order_item_removed_ingredient_removed_id_fkey', '__order_item_removed_ingredient', 'ingredient', ['removed_id'], ['id'])
    op.drop_constraint(None, '__order_item_added_ingredient', type_='foreignkey')
    op.drop_constraint(None, '__order_item_added_ingredient', type_='foreignkey')
    op.create_foreign_key('__order_item_added_ingredient_added_id_fkey', '__order_item_added_ingredient', 'ingredient', ['added_id'], ['id'])
    op.create_foreign_key('__order_item_added_ingredient_order_item_id_fkey', '__order_item_added_ingredient', 'order_item', ['order_item_id'], ['id'])
    # ### end Alembic commands ###
