"""add delivery price to restaurant

Revision ID: 4bbe71157911
Revises: 230e07155bad
Create Date: 2025-10-30 17:18:35.208502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bbe71157911'
down_revision: Union[str, None] = '230e07155bad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order', 'unique_code',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.add_column('restaurant', sa.Column('delivery_price', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurant', 'delivery_price')
    op.alter_column('order', 'unique_code',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    # ### end Alembic commands ###
