services:

  db:
    image: postgres:17.5
    container_name: db
    restart: always
    ports:
      - "5432:5432"
    networks:
      - vivat-network
    volumes:
      - db-volume:/var/lib/postgresql/data
    env_file:
      - .env

  backend:
    build:
      context: .
    container_name: backend
    restart: always
    working_dir: /server
    ports:
      - "8000:8000"
    networks:
      - vivat-network
    depends_on:
      - db
    env_file:
      - .env
    environment:
      ALLOWED_ORIGINS: ${ALLOW_ORIGINS}
      ALLOW_METHODS: ${ALLOW_METHODS}
      ALLOW_HEADERS: ${ALLOW_HEADERS}
      ALLOW_CREDENTIALS: ${ALLOW_CREDENTIALS}
    volumes:
      - ./app/:/server
    command: >
      sh -c "cd /server &&
      alembic upgrade head &&
      gunicorn main:create_application --workers 1 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000"

volumes:
  db-volume:

networks:
  vivat-network:
    driver: bridge
